---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroupns_mode: host
    pre_build_image: true 

role_name_check: 1
scenario:
  create_sequence:
#    - dependency
    - create
#    - prepare
  check_sequence:
#    - dependency
#    - cleanup
    - destroy
    - create
#    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
#    - dependency
    - create
#    - prepare
    - converge
  destroy_sequence:
#    - dependency
#    - cleanup
    - destroy
  test_sequence:
#    - dependency
#    - cleanup
    - destroy
    - syntax
    - create
#    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
#    - cleanup
    - destroy
