---
- name: Converge
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Test roll-op devnet installation
      ansible.builtin.include_role:
        name: upnodedev.op.roll_op
      vars:
        ansible_user: root
        roll_op_seed_phrase: 'wet hole defense spread typical coffee dragon pumpkin size sad eight profit'
        roll_op_state: started