- name: Prepare the Molecule Test Resources
  hosts: all
  tasks:
    - name: Create a login user
      user:
        name: ubuntu
        password: "{{ 'ubuntu_pwd' | password_hash('sha512', 'salt') }}"
        groups: 
         - sudo
        state: present
        shell: /bin/bash
